module: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-ai-common
package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/tpm-ai-common/store/promptqueueitem
entities:
- file-name: ./prompt-queue-item.yml
  document: true
- file-name: ./bucket-path-pair.yml
- file-name: ./bid-et-pair.yml

# @tpm-schematics:start-region("bottom-file-section")
# @tpm-schematics:end-region("bottom-file-section")
