
anthropic:
  api-key: ${ANTHROPIC_API_KEY}
  request-timeout: 600s
  verbose: true
  mockup:
    http-client:
      skv: true
    enabled: false
    host-name: localhost
    server-port: 3001
    http-scheme: http
    endpoint: /api/anthropic

ollama:
  url: "http://localhost:11434"
  verbose: true
