
rest-client:
  timeout: "15s"
  skip-verify: true
  trace-op-name: "rtp-%s"

aws-s3:
  - name: default
    endpoint: ${AWS_S3_ENDPOINT}
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    buckets:
      - tag: pgm
        buckets:
          - ${COB_GAME_DEPLOY_ENV_PREFIX}-{domain}-{site}-queue-awce
        path: "pgm"
      - tag: copy
        buckets:
          - ${COB_GAME_DEPLOY_ENV_PREFIX}-{domain}-{site}-queue-awce
        path: "copy/{container}"

mongo-db:
  - name: default
    host: ${MONGODB_HOST_ENV}
    db-name: ${MONGODB_DB_ENV}
    user: ${MONGODB_USR_ENV}
    pwd: ${MONGODB_PWD_ENV}
    authSource: ${MONGODB_AUTHSRC_ENV}
    # TLS or PLAIN
    security-protocol: ${MONGODB_SECURITY_PROTOCOL}
    tls:
      skip-verify: ${MONGODB_SKPVER_ENV}
    bulkWriteOrdered: true
    # Admitted values: 1, majority
    write-concern: majority
    write-timeout: 120s
    pool:
      min-conn: 1
      max-conn: 20
      max-wait-queue-size: 1000
      max-wait-time: 1000
      max-connection-idle-time: 30000
      max-connection-life-time: 6000000
    collections:
      - id: site
        name: cob_game_system
      - id: domain
        name: cob_game_system
      - id: session
        name: cob_game_session
      - id: user
        name: cob_game_user
      - id: key-value-package
        name: cob_game_system
      - id: s3-events
        name: cob_game_s3_event
      - id: program
        name: cob_game_source
      - id: copy-cnt
        name: cob_game_source
      - id: copy-lib
        name: cob_game_source
      - id: line
        name: cob_game_source
      - id: node
        name: cob_game_source
      - id: para
        name: cob_game_source
      - id: jobs
        name: cob_game_jobs
      - id: jobs-logs
        name: cob_game_jobs
      - id: artifact
        name: cob_game_artifacts

cobol-parser:
  host-name: localhost
  server-port: 8081
  http-scheme: http
  url: /api/cobol/parse
  http-client:
    timeout: "120s"
    skv: true
    trace-req-name: "smp-{op-name}"
    # retry-count:2
    # retry-wait-time: "200ms"
    # retry-max-wait-time: "1s"
    # retry-on-errors:
    #   - 500

anthropic:
  api-key: ${ANTHROPIC_API_KEY}
  request-timeout: 600s
  verbose: true
  mockup:
    http-client:
      skv: true
    enabled: false
    host-name: localhost
    server-port: 3001
    http-scheme: http
    endpoint: /api/anthropic

ollama:
  url: "http://localhost:11434"
  verbose: true
